### ISSUE TITLE
线程关闭机制是否应该如下操作？

### ISSUE THREAD

**Issue by driftluo** [maboss-YCMan/ziyan#26]
考虑一下，每天晚上重启所有线程是不是有点简单粗暴？
是否在每个线程中，加一个 queue，向主线程发送活着的标识，带上自身的线程名，如果长时间主线程未收到某线程活着的信号，才进行强制结束线程，然后让线程重启。
已经想到方案，打算修改每天强制重启的策略，改成堵塞超过10分钟，即强制关闭

**Comment by Fatekiller23** [comment]
为啥这个issue 直接就26号了？？

**Comment by driftluo** [comment]
已解决
